## YAML script for CI of Ph2_ACF Software/Middleware
## Author: Emery Nibigira (IPHC-Strasbourg, U. of Tennessee)
##         emery.nibigira@cern.ch

## Updates: Lawrence Lee (U. of Tennessee)
##          lawrence.lee.jr@cern.ch

## SETUP ##########

## The pipeline starts when a merge request is created
## or when the CI config is changed

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes: # when any file matching the below is edited, create a pipeline
        - .gitlab/ci/*
        - .gitlab/ci/*/*
        - .gitlab-ci.yml
      when: always
      allow_failure: true

image:
  name: gitlab-registry.cern.ch/cms_tk_ph2/docker_exploration/cmstkph2_ci_c7:latest
  entrypoint: ["/bin/sh","-c"]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - run

## QUALITY ##########

include:
  - .gitlab/ci/code-quality.yml


## BUILD ##########

.build:
  stage: build
  needs: []
  image:
    name: gitlab-registry.cern.ch/cms_tk_ph2/docker_exploration/cmstkph2_ci_c7:latest
    entrypoint: ["/bin/sh","-c"]
  before_script:
    - source ./setup.sh ci
  script:
    - mkdir -p build; cd build
    - cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_PROJECT_DIR/
    expire_in: 1 week

# Stand-alone application, without data streaming
build:StandAlone_woDS:
  extends: .build
  # artifacts:
  #   paths:
  #     - bin/ot_module_test
  #     - bin/commission
  #     - bin/CMSITminiDAQ
  #   expire_in: 1 week





## RUN ##########

.run:
  stage: run
  needs:
    - build:StandAlone_woDS
  before_script:
    - settings/CMSPS.xml .
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
      allow_failure: false
    - when: manual
      allow_failure: true


## PS hybrid
run:PS:
  extends: .run
  script:
    - source ./setup.sh ci
    - ot_module_test -f CMSPS.xml -t -m -a -b --reconfigure
  after_script:
    - cp Results/*/Hybrid.root .
    - gdb bin/ot_module_test core.* -ex where --batch > coreAnalysisPS.log
    - cp coreAnalysis2S.log .
  artifacts:
    paths:
      - Hybrid.root
      - coreAnalysisPS.log
    expire_in: 1 week

