[Producer.ni_mimosa]
NiIPaddr = 192.168.24.2


[LogCollector.log]
# Currently, all LogCollectors have a hardcoded runtime name: log
# the $12D will be converted a data/time string with 12 digits.
EULOG_GUI_LOG_FILE_PATTERN = /home/teleuser/cms_ot_june2022/log/log_$12D.log

[Producer.CMSPixelREF]

# DTB board USB ID
#usbId = "DTB_WS65DL"
usbId = "*"

# pxarCore library verbosity
#verbosity = DEBUGPIPES
verbosity = INFO


[DataCollector.one_dc]

[Monitor.my_mon]

