[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = aida_tlu

[LogCollector.log]

[DataCollector.the_dc]
EUDAQ_MN = StdEventMonitor
EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10
EUDAQ_FW = native
EUDAQ_FW_PATTERN = /home/yotarid/DESY/Dev/sw/run$6R$X
DISABLE_PRINT = 1


[Monitor.StdEventMonitor]

[Producer.ph2producer]
# Define the data collector to be used by the producer
EUDAQ_DC = the_dc

RawDataDirectory = /home/yotarid/DESY/Dev/sw/
TriggerSource = 3
TLUHandshake = 2
TLUTriggerIdDelay = 1
DataHandshakeEnable = false

CommonStubDelay = 45
TriggerMultiplicity = 0

EnableInjection = true
