[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = eudet_tlu

[LogCollector.log]

[Producer.eudet_tlu]
OrMask = 0
VetoMask = 0
TrigRollover = 0

AndMask = 15

#TriggerInterval = 1

DutMask = 9

#HandShakeMode = 17
#HandShakeMode = 3
HandShakeMode = 1

PMTVcntl1 = 795
PMTVcntl2 = 795
PMTVcntl3 = 795
PMTVcntl4 = 795

# Define the data collector to be used by the producer
EUDAQ_DC = the_dc
DISABLE_PRINT = 1


[Producer.ni_mimosa]
TriggerType = 1
Det = MIMOSA26
Mode = ZS2
NiVersion = 1
NumBoards = 6
FPGADownload = 1
OneFrame = 0
IDOffset = 0

MimosaEn_1 = 1
MimosaEn_2 = 1
MimosaEn_3 = 1
MimosaEn_4 = 1
MimosaEn_5 = 1
MimosaEn_6 = 1
# Define the data collector to be used by the producer

EUDAQ_DC = the_dc 
DISABLE_PRINT = 1


[Producer.CMSPixelREF]
# MODULE: 4294
tbmtype = tbm08c
roctype = psi46digv21respin
pcbtype = desytb

tbmFile = "/home/teleuser/cms_ot_june2022/D4294/tbmParameters"
dacFile = "/home/teleuser/cms_ot_june2022/D4294/dacParameters"
trimFile = "/home/teleuser/cms_ot_june2022/D4294/trimParameters"
maskFile = "/home/teleuser/cms_ot_june2022/D4294/maskFile.dat"
i2c = 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

# overwrite DAC parameters:
#vibias_bus = 90 # for eff ?
#vdig = 9
vthrcomp = 88

# DTB related settings:
# external clock on/off
external_clock = 0

# Select trigger source ("async_dir" for external with TBM):
trigger_source = async_dir

hubid = 31

# Scope outputs:
signalprobe_d1 = clk
signalprobe_d2 = ctr
#signalprobe_a2 = sdata2

# Supply voltages and current limits:
#vd = 2.800
#va = 1.900
vd = 3.000
va = 1.900
id = 1.190
ia = 1.190

# DTB Timing
clk = 13
ctr = 13
sda = 28
tin = 18
deser160phase = 4
level = 12

# software delay + cable delay = WBC = 100
triggerlatency = 81

# Other settings (producer & pxarCore)
# Waiting time (ms) before stopping DAQ (TLU is slow in stopping triggering...)
tlu_waiting_time = 4000

EUDAQ_DC = the_dc


[DataCollector.the_dc]
EUDAQ_MN = StdEventMonitor
EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10
EUDAQ_FW = native
EUDAQ_FW_PATTERN = /data3/2022-06_CMSOT/run$6R$X
DISABLE_PRINT = 1


[Monitor.StdEventMonitor]


